language: c

notifications:
  irc:
    - "chat.freenode.net#ossec-dev"

env:


- DB=no  TYPE=server GEOIP=no
- DB=no  TYPE=server GEOIP=yes
- DB=yes TYPE=server GEOIP=no
- DB=yes TYPE=server GEOIP=yes
- DB=no  TYPE=agent  GEOIP=no
- DB=no  TYPE=windows_agent  GEOIP=no



compiler:
- gcc



before_script:
- if [[ "$DB" == "mysql"  ]]; then ( cd src && make setdb  ); fi
- if [[ "$GEOIP" == "yes"  ]]; then ( sudo apt-get install geoip-bin geoip-database libgeoip-dev libgeoip1 ); fi
- if [[ "$GEOIP" == "yes"  ]]; then ( cd src && make setgeoip ); fi
- if [[ "$OSSEC_TYPE" == "windows_agent" ]]; then ( sudo apt-get install mingw32 mingw32-binutils mingw32-runtime nsis ); fi



script:
- if [[ "$OSSEC_TYPE" == "server" ]]; then ( cd src && make all ); fi
- if [[ "$OSSEC_TYPE" == "server" ]]; then ( cd src && sudo make server ); fi
- if [[ "$OSSEC_TYPE" == "server" ]]; then ( cd contrib/ossec-testing && sudo python runtests.py ); fi
- if [[ "$OSSEC_TYPE" == "windows_agent" ]]; then ( cd src && make windows_agent ); fi
- if [[ "$OSSEC_TYPE" == "agent" ]]; then ( cd src && make all ); fi
- if [[ "$OSSEC_TYPE" == "agent" ]]; then ( cd src && sudo make agent ); fi

before_deploy:
- mkdir travis-builds
- if [[ "$OSSEC_TYPE" == "windows_agent" ]]; then ( cp src/win-pkg/ossec-agent.exe travis-builds/ossec-agent-bid:$TRAVIS_JOB_NUMBER-br:$TRAVIS_BRANCH.exe ); fi


deploy:
  provider: s3
  access_key_id: AKIAIJNKNIB2ARNBYMOA
  secret_access_key:
    secure: "miwB5++34wYPUHC6TuuOSkvJhZrTZ3N70dnVjB4mwwlDn6ARTZXWfMk6KU35VTuIGftFybY/HEWq2WEQOQTHe7sAfknJ2oeKU+YtGP5ydFrummFPjDTJg5Q4Qz4ikwyl9t/j840YJmFCvlDu29NhMYQd9izJJqCssCpkA8ZF2f4="
  bucket: ossec-travis-ci
  upload-dir: ossec-hids
  local-dir: travis-builds
